### PR TITLE
Upgrading swagger-ui to 3.7.0

### PR DESCRIPTION
**Pull request by kasecato**
## What's this PR do/fix?
I upgraded swagger-ui from 2.2.10 to 3.7.0. I fixed only the front end, I want someone to fix the back end. ~~And I have not handled the error yet.~~

- [x] Swagger-UI 3.7.0
- [x] OAuth
- [x] Error Handling

## Are there unit tests? If not how should this be manually tested?
- Browser compatibility 

| Feature | IE | Edge | Firefox | Chrome | Safari |
|---------|---|------|--------|---------|-------|
|[Async functions](https://caniuse.com/#feat=async-functions)|-|15|56|61|10.1|
|[Fetch](https://caniuse.com/#feat=fetch)|-|15|56|49|10.1|
|[Allow functions](https://caniuse.com/#feat=arrow-functions)|-|15|56|49|10.2|
|[Fonts](https://google-webfonts-helper.herokuapp.com/fonts)|9|15|3.6|6|5.1|

## Any background context you want to provide?
I started using this great library at work from this month, I thought the UI was old for me, so I fixed it.

## What are the relevant issues?
- #1870 - The lasted version supported for swagger3.x?
- #1729 - Status of support for v3.0.2 of swagger UI
- #1960 - Upgrade to swagger-ui 3.0
- #2000 - Upgrade to latest version of swagger-ui (3.1.5)

### CODE REVIEW

**Comment by dilipkrish** [comment]
This is awesome. Thank you for helping out with this. 👌🏼

**Comment by sebasira** [comment]
+1

I guess you're still reviewing it. I'll stay tuned waiting for this to be merged

**Comment by kasecato** [comment]
It's done. It will work  as it is thought the  settings of Swagger UI 3.x and 2.x have a lot of changed... I think it's  better to rewrite back-end settings API (e.g. /swagger-resources/configuration/ui and security) for 3.x.

**Comment by dilipkrish** [comment]
@kasecato Would you mind making those changes as well since you would know better how its changed?

**Comment by sebasira** [comment]
Would it be a Release or I would just need to do it by myself? If not, please explain me how

**Comment by kasecato** [comment]
@dilipkrish I designed it for swagger UI 3.x. It will work even if you do not change, but please implement it if necessary.

# Springfox

## UI Config API: `/swagger-resources/configuration/ui`
UI Config API | Swagger UI 3.7.0
------------- | ----------------
validatorUrl | `validatorUrl`
docExpansion | `docExpansion`
apisSorter | not available (🔨mapping to `tagsSourter` and `operationsSorter`, temporary. I'd like to set this separately)
defaultModelRendering | `defaultModelRendering`
requestTimeout | not available (🔨delete)
supportedSubmitMethods | not available (🔨delete)
jsonEditor | not available (🔨delete)
showRequestHeaders | not available (🔨delete)

## Serurity Config API: `/swagger-resources/configuration/security`
Serurity Config API | Swagger UI 3.7.0
------------- | ----------------
clientId | `client_id`
clientSecret | `client_secret`
realm | `realm`
appName | `appName`
apiKey | not available (🔨delete)
apiKeyVehicle | not available (🔨delete)

## Resources API: `/swagger-resources`
Resources API | Swagger UI 3.7.0
------------- | ----------------
name | `name`
location | `url` (🔨change name to `url`)
swaggerVersion | not available (🔨delete)

# [Swagger UI 3.7.0](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md)

## Core

Springfox set | Parameter Name | Description
--- | --- | ---
👌 null | `configUrl` | `String`. URL to fetch external configuration document from.
👌 "#swagger-ui" | `dom_id` |`String`, **REQUIRED** if `domNode` is not provided. The id of a dom element inside which SwaggerUi will put the user interface for swagger.
👌 null | `domNode` | `Element`, **REQUIRED** if `dom_id` is not provided. The HTML DOM element inside which SwaggerUi will put the user interface for swagger. Overrides `dom_id`.
👌 {} | `spec` | `Object={}`. A JS object describing the OpenAPI Specification. When used, the `url` parameter will not be parsed. This is useful for testing manually-generated specifications without hosting them.
👌 "" | `url` | `String`. The url pointing to API definition (normally `swagger.json` or `swagger.yaml`). Will be ignored if `urls` or `spec` is used.
🔨 API `/swagger-resources` (change `location` to `url`) | `urls` | `String`. An array of API definition objects (`{url: "<url>", name: "<name>"}`) used by Topbar plugin. When used and Topbar plugin is enabled, the `url` parameter will not be parsed. Names and URLs must be unique among all items in this array, since they're used as identifiers.
🤔 null (I think someone needs this) | `urls.primaryName` | `String`. When using `urls`, you can use this subparameter. If the value matches the name of a spec provided in `urls`, that spec will be displayed when Swagger-UI loads, instead of defaulting to the first spec in `urls`.

## Plugin system

Read more about the plugin system in the [Customization documentation](/docs/customization/overview.md).

Springfox set | Parameter Name | Description
--- | --- | ---
👌 "StandaloneLayout" | `layout` | `String="BaseLayout"`. The name of a component available via the plugin system to use as the top-level layout for Swagger-UI.
👌 [SwaggerUIBundle.plugins.DownloadUrl] | `plugins` | `Array=[]`. An array of plugin functions to use in Swagger-UI.
👌 [SwaggerUIBundle.presets.apis,SwaggerUIStandalonePreset] | `presets` | `Array=[SwaggerUI.presets.ApisPreset]`. An array of presets to use in Swagger-UI. Usually, you'll want to include `ApisPreset` if you use this option.

## Display

Springfox set | Parameter Name | Description
--- | --- | ---
👌 true | `deepLinking` | `Boolean=false`. If set to `true`, enables deep linking for tags and operations. See the [Deep Linking documentation](/docs/usage/deep-linking.md) for more information.
👌 false | `displayOperationId` | `Boolean=false`. Controls the display of operationId in operations list. The default is `false`.
👌 1 | `defaultModelsExpandDepth` | `Number=1`. The default expansion depth for models (set to -1 completely hide the models).
👌 1 | `defaultModelExpandDepth` | `Number=1`. The default expansion depth for the model on the model-example section.
🔨 `defaultModelRendering` | `defaultModelRendering` | `String=["example"*, "model"]`. Controls how the model is shown when the API is first rendered. (The user can always switch the rendering for a given model by clicking the 'Model' and 'Example Value' links.)
👌 false | `displayRequestDuration` | `Boolean=false`. Controls the display of the request duration (in milliseconds) for Try-It-Out requests.
🔨 `docExpansion` | `docExpansion` | `String=["list"*, "full", "none"]`. Controls the default expansion setting for the operations and tags. It can be 'list' (expands only the tags), 'full' (expands the tags and operations) or 'none' (expands nothing).
👌 false | `filter` | `Boolean=false OR String`. If set, enables filtering. The top bar will show an edit box that you can use to filter the tagged operations that are shown. Can be Boolean to enable or disable, or a string, in which case filtering will be enabled using that string as the filter expression. Filtering is case sensitive matching the filter expression anywhere inside the tag.
👌 null | `maxDisplayedTags` | `Number`. If set, limits the number of tagged operations displayed to at most this many. The default is to show all operations.
🔨 `apisSorter` | `operationsSorter` | `Function=(a => a)`. Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically), 'method' (sort by HTTP method) or a function (see Array.prototype.sort() to know how sort function works). Default is the order returned by the server unchanged.
👌 false | `showExtensions` | `Boolean=false`. Controls the display of vendor extension (`x-`) fields and values for Operations, Parameters, and Schema.
🔨 `apisSorter` | `tagsSorter` | `Function=(a => a)`. Apply a sort to the tag list of each API. It can be 'alpha' (sort by paths alphanumerically) or a function (see [Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) to learn how to write a sort function). Two tag name strings are passed to the sorter for each pass. Default is the order determined by Swagger-UI.

## Network

Springfox set | Parameter Name | Description
--- | --- | ---
👌 base url + "/webjars/springfox-swagger-ui/oauth2-redirect.html"  | `oauth2RedirectUrl` | `String`. OAuth redirect URL.
👌 (a => a) | `requestInterceptor` | `Function=(a => a)`. MUST be a function.  Function to intercept remote definition, Try-It-Out, and OAuth2 requests.  Accepts one argument requestInterceptor(request) and must return the potentially modified request.
👌 (a => a) | `responseInterceptor` |`Function=(a => a)`. MUST be a function.  Function to intercept remote definition, Try-It-Out, and OAuth2 responses.  Accepts one argument responseInterceptor(response) and must return the potentially modified response.
👌 true | `showMutatedRequest` | `Boolean=true`. If set to `true`, uses the mutated request returned from a requestInterceptor to produce the curl command in the UI, otherwise the request before the requestInterceptor was applied is used.
🔨 `validatorUrl` | `validatorUrl` | `String="https://online.swagger.io/validator" OR null`. By default, Swagger-UI attempts to validate specs against swagger.io's online validator. You can use this parameter to set a different validator URL, for example for locally deployed validators ([Validator Badge](https://github.com/swagger-api/validator-badge)). Setting it to `null` will disable validation.

## Macros

Springfox set | Parameter Name | Description
--- | --- | ---
👌 null | `modelPropertyMacro` | `Function`. Function to set default values to each property in model. Accepts one argument modelPropertyMacro(property), property is immutable
👌 null | `parameterMacro` | `Function`. Function to set default value to parameters. Accepts two arguments parameterMacro(operation, parameter). Operation and parameter are objects passed for context, both remain immutable

## [OAuth 2.0](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md)
Springfox set | Config Name | Description
--- | --- | ---
🔨 `clientId` | client_id | Default clientId. MUST be a string
🔨 `clientSecret` | client_secret | Default clientSecret. MUST be a string
🔨 `realm` | realm | realm query parameter (for oauth1) added to `authorizationUrl` and `tokenUrl` . MUST be a string
🔨 `appName` | appName | application name, displayed in authorization popup. MUST be a string
🔨 `scopeSeparator` | scopeSeparator | scope separator for passing scopes, encoded before calling, default value is a space (encoded value `%20`). MUST be a string
👌 {} | additionalQueryStringParams | Additional query parameters added to `authorizationUrl` and `tokenUrl`. MUST be an object
👌 false | useBasicAuthenticationWithAccessCodeGrant | Only activated for the `accessCode` flow.  During the `authorization_code` request to the `tokenUrl`, pass the [Client Password](https://tools.ietf.org/html/rfc6749#section-2.3.1) using the HTTP Basic

**Comment by dilipkrish** [comment]
So am I right in assuming 
👌 - No change required
🔨 - TODO items for springfox?

Is it ready to play with?

**Comment by dilipkrish** [comment]
I think I understand (somewhat!) Thanks so much for your effort @kasecato! Im sure people using it will be thrilled once its released!

**Comment by liudonghua123** [comment]
Nice work 👍, exactly what I want.

**Comment by dilipkrish** [comment]
Thank you so much @kasecato!

**Comment by sebasira** [comment]
Do you know when you are plannin to release v2.8.0? Or can someone explain me how to use this on my Spring Boot (Gradle) App?

I really need this to release my app and expose its API. And I need it because it has features (like working headers for HTTP OK Response) that works

**Comment by dilipkrish** [comment]
You can use the snapshot version if its urgent. But the plan is to release it in the next couple of weeks.

**Comment by sebasira** [comment]
Hello guys! Sorry to interrupt again. I've updated my gradle to v2.8.0 but yet the UI is the same as before not the new one.

Also looking at the docs when it talks about the UI the screenshot is not as the the latest version of Swagger.

Am I doing something wrong?
Thanks for your time

**Comment by dilipkrish** [comment]
Are you talking about swagger-ui 3.x or open api 3.x? If its the latter, springfox doesnt support it yet. Swagger-ui 3.x is available in springfox version >= 2.8.0

**Comment by technician21** [comment]
Hello kasecato, dilipkrish,
is there an easy way to switch back to the old simple theme design?
Have switched springfox-swagger2 to 2.8.0 but have saved springfox-swagger-ui at 2.7.0, is it safe?
The version springfox-swagger2 2.7.0 had dependency discrepancies with google guava in our project, but I would to keep similar view with existed services.
Thanks.

**Comment by user20161119** [comment]
> Are you talking about swagger-ui 3.x or open api 3.x? If its the latter, springfox doesnt support it yet. Swagger-ui 3.x is available in springfox version >= 2.8.0

hi,i use http://dev.wx.yqfoodec.com/swagger-ui.html url to view api document,how can i config to upgrade to SWAGGER-UI 3.x? i

**Pull request merged**
