### PR TITLE
Rich alternate type rule

### PR DESCRIPTION
**Pull request by dangoslen**
#### What's this PR do/fix?
This PR attempts to address the first part of issue #918, which creates the ability to retrieve properties as if it were the original type instead of the alternate.

#### Are there unit tests? If not how should this be manually tested?
I believe I have added the tests needed.

#### Any background context you want to provide?
I tried to keep changes small at first to incorporate feedback sooner rather than later. I'm open to improvements for sure!

#### What are the relevant issues? 
#918

### CODE REVIEW

**Comment by dilipkrish** [comment]
@dangoslen Just getting around to reviewing it. 

I was wondering, since propertyHost is a new method (additive not breaking), why not have AlternateTypeRule remain as it is (i.e. not turn it into an interface) and just add the new method to it.

And keep everything else the same, like you have it. The reason Im suggesting that is 
1. it maintains backwards compatibility and i could pull it in before 2.9 which I plan to release this weekend or early next week
2. Still introduce the new behavior of exposing the original object.
3. Also, I like the idea of introducing the interface, but Im a little ambivalent about making Simple/Rich alternate type rules public. I'd rather just expose a factory method that creates either one of the interface.

I could be swayed either way, let me know what you think? Also would you mind squashing your merge commit?

**Comment by dangoslen** [comment]
Fair points. No need for another layer of abstraction there. Now that I re-look, I think I got halfway through and thought the same thing, and forgot to back it out. 

Per point 3, I _thought_ the `AlternateTypeRule` was public already... was it not. I do like the idea of static factory methods though, which reminds me I never added the helper function to create a `RichAlternateType` on the `Docket`. I'll at least get the helper methods added to the `Docket` as that was included in the original feature request anyhow.

Also, and this is where my newb status to OpenSource comes in, how would I squash the merge commit after its been committed? I've tried to follow a few articles using `git rebase -i`, but to no avail. Is the best option to reset to before the merge and run a new merge command? Sorry for the newb status

**Comment by dilipkrish** [comment]
@dangoslen 

> Sorry for the newb status

We're all newbs sometime or the other. I still learn things about git and github every day. Sorry I assumed you'd know. The reason is the quality of your PR; each commit tells a story. It makes reviewing so easy. It is also why the empty merge commit stands out :)

I believe if you do the following it should work. That should remove the empty commit.

```bash
# Assumes your current branch is the one you're working this PR on 
# and you dont have any local changes that are not committed.
git fetch origin master
git rebase origin/master
```

Yeah  `AlternateTypeRule` was created when I didn't put much thought into whether something was public or not :) In OSS you learn pretty fast that thats not a great idea. There is a [factory/helper however](https://github.com/springfox/springfox/blob/5ce78b962a0a95edddcb29e676b80cb7163bf87b/springfox-core/src/main/java/springfox/documentation/schema/AlternateTypeRules.java#L37-L59) that tries to make it easier to create these rules with the right order.

**Comment by dangoslen** [comment]
👍 Thanks for the help there. Wasn't aware git could do a merge and then a rebase after the fact. 

Ironically, after getting to the point where I wanted to test out the `Docket` class and do final validation that using the `RichAlternateTypeRule` returned the right swagger .json, it looks like the feature exists using a normal `AlternateTypeRule` (or direct substitution). 

I added a new field of `LocalDate` in the `User` model in the petstore example and then added the `@ApiModelProperty` to the field and it had the right values without modifying the `Docket` in `Swagger2SpringBoot` example configuration. Maybe I misunderstood the feature request.

With that being said, maybe this PR is the wrong way to go and I should switch to try to get the defaults for a property added (which is the second piece mentioned in the original request). 

Thoughts?

**Comment by dilipkrish** [comment]
> I added a new field of LocalDate in the User model in the petstore example and then added the @ApiModelProperty to the field and it had the right values without modifying the Docket in Swagger2SpringBoot example configuration. 

Im surprised that it does. Perhaps it was fixed since the issue was created. The initial idea was to supplement additional metadata using fluent builders as opposed to referring annotations, which involves few reflection calls. I'll revisit the code and see what is missing.

**Pull request closed without merging**
