### PR TITLE
Issue 2932

### PR DESCRIPTION
**Pull request by alienisty**
#### What's this PR do/fix?
Adds compatibility with Spring Boot 2.2.1

#### Are there unit tests? If not how should this be manually tested?
All existing tests pass

#### Any background context you want to provide?
Small improvement/changes in the way endpoints are named

#### What are the relevant issues?
#2932

### CODE REVIEW

**Comment by AndreasKl** [comment]
@alienisty Is this a duplicate of? https://github.com/springfox/springfox/pull/3159

**Comment by alienisty** [comment]
It looks like it addresses the same issue.
Last time I checked spring boot was 2.2.1 and I made the change for that
version, so I guess 3159 is more up to date.

Alessandro (Alex) Nistico
alienisty@gmail.com

"Any system like Eternity, which allows men to choose their own future,
will end
 by choosing safety and mediocrity, and in such a Reality the stars are out
of reach."

The End of Eternity - Isaac Asimov

**Comment by dilipkrish** [comment]
@alienisty thank you for this PR. Closing this one, but would you still be up for a new PR for the gradle build system changes still in this PR that is useful?

**Comment by dilipkrish** [comment]
Duplicate of #3159

**Comment by alienisty** [comment]
@dilipkrish,
do you refer to the commit for fixing the plugin for eclipse?

**Pull request closed without merging**
