### PR TITLE
Added response message examples support (#1570)

### PR DESCRIPTION
**Pull request by Q1nt**
Added new 'examples' property to ResponseMessage with corresponding
change in ResponseMessageBuilder.
Updated corresponding mapping logic, to populate response message
examples instead of an empty map.

It is related to issue #1570 and could be considered as the first step to adding response examples support.

### CODE REVIEW

**Comment by jasouyris** [comment]
You beat me to it, Q1nt! I need this feature for my project and yesterday I noticed that swagger2Core dependency was upgraded to 1.5.20 (meaning that ApiResponse.examples() is now available), so I spent some time last night on adding support for it. I finished quite late so I decided to wait for today to create the PR, and to my surprise, I noticed that you've added the examples field to the ResponseMessage already.

[Here's my PR](https://github.com/springfox/springfox/pull/2515), I took a different approach: Instead of representing examples as a Map<String, Object> (as you did), I used the already existing springfox.documentation.schema.Example structure so I have it as a List of Example.

But now that I think about it, maybe using the Example structure is a little bit over-engineered, because that means I need to transform:

io.swagger.annotations.ExampleProperty -> springfox.documentation.schema.Example -> Entry<String, Object>

instead of just going straight:

io.swagger.annotations.ExampleProperty -> Entry<String, Object>

I'll wait to see what the rest thinks, if they decide to keep your approach, I'll create a new PR after they've merged your changes.

**Comment by Q1nt** [comment]
@jasouyris sorry about that :)
Wasn't aware that someone working on it too.
Actually, I can't see anything wrong with your approach with the list of examples.
I stuck to Map<String, Object> as it was a simpler way.

Anyway, I would be happy with any of options, your or mine.
Let's see what the maintainers will say.
@dilipkrish any thoughts?

**Comment by dilipkrish** [comment]
Thank you both for the PRs! It is much appreciated! Havent had a chance to look yet, I'll try to incorporate the best of both of your PR.

**Comment by Q1nt** [comment]
Hello, @dilipkrish! Any updates on this?

**Comment by dilipkrish** [comment]
The PR needs conflicts resolved, but I was going pull these in shortly

**Comment by Q1nt** [comment]
Any actions required from my (our) side?
Or you gonna do it on your own?

**Comment by Q1nt** [comment]
Seems like I've done it in a wrong way with rebase, sorry for that, it's actually my first PR :|

**Comment by dilipkrish** [comment]
@Q1nt no worries... I'll fix it up. For a first PR 👏 for putting discrete commits and splitting your work into incremental commits. What you probably did there was to not rebase against the origin branch. 

When I work on PRs I find it easier to understand when I name my upstreams accordingly. For e.g. I usually name `springfox/springfox` as the `origin` upstream, and my fork as `dilipkrish`, that way its easy to remember which upstream is mine vs. which upstream is the repo Im sending a pull request for. Let me know if you have any questions. Id be happy to walk you through it.

**Comment by dilipkrish** [comment]
@Q1nt thanks for the PR. Sorry I took the easier route than fixing up this PR, which is essentially very similar.

**Comment by Q1nt** [comment]
@dilipkrish 
No problem! 

Is there any chance those changes will be available as part of 2.9.3 version?

**Comment by dilipkrish** [comment]
No unfortunately, it'll be part of 3.0.0

**Pull request closed without merging**
