### PR TITLE
Issue 3255

### PR DESCRIPTION
**Pull request by shouldnotappearcalm**
#### What's this PR do/fix?
fix `@Size` annotation does not work properly on `List`
#### Are there unit tests? If not how should this be manually tested?
You can write the following code in the bean
```Java
@ApiModelProperty("list1")
@Size(min = 1, max = 200, message = "1-200")
private List<String> list1;
```
Then you can see in the generated swagger json
```json
list1:- {
type: "array",
description: "list1",
items:- {
  type: "string"
},
maxItems: 200,
minItems: 1
}
```

#### Any background context you want to provide?
As above
#### What are the relevant issues?
[3255](https://github.com/springfox/springfox/issues/3255)

### CODE REVIEW

**Comment by shouldnotappearcalm** [comment]
I looked at the test methods in the `EnumMapperSpec` class, but I feel that `ArrayProperty` class does not seem to be particularly suitable for current methods, because it does not have properties such as `enums `and `minimum`. Do I need to add a test method? @dilipkrish

**Comment by dilipkrish** [comment]
You can add a new method for your test. Without that there is no safety net for your change.

**Comment by shouldnotappearcalm** [comment]
Hi,I have added the corresponding unit tests for the new code. Please take a look when you are free. @dilipkrish

**Comment by dilipkrish** [comment]
Thank you @shouldnotappearcalm

**Pull request merged**
