### PR TITLE
Springfox #845: Configuration for global Operation-Parameters. (Documentation)

### PR DESCRIPTION
**Pull request by GitVhaos**

### CODE REVIEW

**Comment by GitVhaos** [comment]
@dilipkrish Like asked  I added documentation for the new feature

**Comment by dilipkrish** [comment]
@GitVhaos failing compilation... its a living document :)

Also you want to squash your commits?

**Comment by GitVhaos** [comment]
Unfortunately I currently only can edit files via GitHub, so I´m unable to squash them..
Fixed the broken docu build :-)

**Comment by dilipkrish** [comment]
@GitVhaos this is not merging cleanly. I think we're losing documentation if I pull it in as is

**Comment by dilipkrish** [comment]
@GitVhaos :rotating_light:

**Comment by GitVhaos** [comment]
@dilipkrish It seems that the conflicts can be easily solved, but i`m currently on a business trip and will be unable to migrate it until end of next week. If it should be merged earlier, maybe u can migrate it?

**Comment by dilipkrish** [comment]
@GitVhaos should I close this one?

**Comment by GitVhaos** [comment]
No further actions required. Solved via another pull-request.

**Pull request closed without merging**
