### PR TITLE
Fix method sort order (#182 )

### PR DESCRIPTION
**Pull request by MaksimOrlov**
If controller class contains overloaded methods, or methods types with same names it leads to instability of a sort order and influence to output definitions, it changes from run to run.

Spring Data Rest bean names for AssociationAction in some cases can not be defined. In that case Entity class name will be used.

That PR fixes all cases that could lead to instability of definitions.

### CODE REVIEW

**Comment by nbv2222** [comment]
should it be merge?

**Comment by mikhilvikram** [comment]
When is this likely to be merged?

**Comment by goemen** [comment]
Can this ticket be given a higher priority please

**Comment by dilipkrish** [comment]
Sorry this took so long @MaksimOrlov!

**Pull request merged**
