### PR TITLE
Fix #3587, allow strict style-src CSP

### LINKED ISSUE #3587: Swagger UI requires unsafe-inline style-src CSP
Please take the time to search the repository, if your question has already been asked or answered.

- [X] What version of the library are you using?

```
implementation("io.springfox:springfox-boot-starter:3.0.0")
```

Is it the latest version? 

**Yes**

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test.

https://github.com/springfox/springfox/blob/758113378de02fd339916f60810abc1d12bb547b/springfox-swagger-ui/src/web/swagger-ui.html#L11-L29

https://github.com/springfox/springfox/blob/758113378de02fd339916f60810abc1d12bb547b/springfox-swagger-ui/src/web/swagger-ui.html#L34

Are both incompatible with a strict CSP and require `style-src: unsafe-inline`, which is not acceptable from a security perspective.

### PR DESCRIPTION
**Pull request by lol768**
#### What's this PR do/fix?
Refer to issue.
#### Are there unit tests? If not how should this be manually tested?

No, set `Content-Security-Policy: style-src 'self'` and verify the swagger-ui page renders as expected.

#### Any background context you want to provide?
Refer to issue.

#### What are the relevant issues?
#3587

### CODE REVIEW

**Comment by lol768** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

ffs, lack of review doesn't suddenly make the PR useless

**Review by chrisbendel — APPROVED** [review]

**Comment by lol768** [comment]
ffs, lack of review doesn't suddenly make the PR useless

**Comment by lol768** [comment]
ffs, lack of review doesn't suddenly make the PR useless

**Review by chrisbendel — APPROVED** [review]

**Comment by lol768** [comment]
.

**Comment by lol768** [comment]
.

**Pull request closed without merging**
