### PR TITLE
#675 Initial approach to adding @Api(description) to the tags output

### PR DESCRIPTION
**Pull request by kevinconaway**
@dilipkrish I took a stab at fixing #675 

I refactored `ResourceGroupingStrategy` to use the `ResourceGroup` to get the resource description.  From my reading of the code base, this didn't need to be at the level of an individual handler method.

It looks like you could also apply the same logic to `getResourcePosition` or simply remove it all together because it didn't really look used in the production code outside of `ClassOrApiAnnotationResourceGrouping`

### CODE REVIEW

**Comment by dilipkrish** [comment]
@kevinconaway thanks for the PR! A quick glance through it it seems like a good fix, however, I'll wait to merge it in for a couple of reasons:
- getResourceDescription doesn't belong in ResourceGroupingStrategy, So I was going to refactor that some so that the responsibility is separated.
- Secondly, a lot of this cruft is there support swagger 1.2 side by side and we're slowly reworking the internals of the swagger 1.2 codebase to be more general purpose; for e.g. swagger 2.0 doesn't have a concept of Listing references. 
- Lastly I'm :watch:  for swagger-core to change its package name to release 2.0.2 patch with the new swagger-core 1.5 release, so I don't want to pull in new changes before that happens.

**Comment by kevinconaway** [comment]
Thanks for the quick response.  Any idea on a timeline for the above?

The top level API descriptions are the first thing end user sees when they view the Swagger docs so I'd like to be able to make a good impression when we release our API documentation.

**Comment by dilipkrish** [comment]
@kevinconaway if you modify the PR such that it preserves backwards compatibility, i'll take merge the pr. ResourceGroupingStrategy is a public api, so I suspect there will be atleast a few custom implementations out in the wild. This change should not break those library consumers. Ideally we want to give atleast a (minor) version for the api consumers to catchup with deprecated apis.

I'd say re-instate the the deleted api and mark as deprecated.

**Comment by dilipkrish** [comment]
@kevinconaway oops! we might have stepped on each others feet here... I just pushed an updated that touched a lot of files

**Comment by kevinconaway** [comment]
I reverted the change to `ResourceGroupingStrategy` per your request, I understand and appreciate your concern for keeping the spi api stable.

**Comment by kevinconaway** [comment]
I pulled in your changes locally and the project built fine without any conflicts. I pushed the latest to my branch so we should be OK there.

**Comment by dilipkrish** [comment]
I squashed the merge commit, and I've pulled it in to master. Thanks for the pr :metal:

**Pull request closed without merging**
