### PR TITLE
Add support for api model property positions.

### PR DESCRIPTION
**Pull request by sbuettner**
Related to #766

### CODE REVIEW

**Comment by dilipkrish** [comment]
I think `TypeForTestingPropertyPositions` its missing the [apache license preamble](https://github.com/springfox/springfox/blob/master/config/apache-copyright.header)

**Comment by sbuettner** [comment]
Don't hesitate to change my tests since i am not that firm with the whole test infrastructure and test data creation. :smile:

**Comment by dilipkrish** [comment]
Thanks a lot for fixing this lingering issue!! :metal:

**Comment by sbuettner** [comment]
@dilipkrish Hope i could help. Great project! Rock on.

**Pull request merged**
