### PR TITLE
Support for JSR-303: @Pattern annotation #1296

### PR DESCRIPTION
**Pull request by igor-sokolov**
#### What's this PR do/fix?
It introduces a basic support of `@Pattern` annotation. It was discussed in the issue: https://github.com/springfox/springfox/issues/1296
#### Are there unit tests? If not how should this be manually tested?
Yes,  added unit tests similar to already existed for `SizeAnnotationPlugin`. Additionally I tested it locally in project that uses Springfox for document generation. The result YAML file contained  pattern ("pattern":"^[A-Z]{3}$"}). It was also rendered on UI but it was not the perfect, I guess due to overlapping in hint sections, one from first field (double) and the second from message field with pattern restriction. 
#### Any background context you want to provide?
I didn't performed any validation of provided in `@Pattern` annotation value, the value just extracted and transferred to Swagger Model object. Ideally it should be validated and also checked that this is not simple a valid RegExp but valid as well for JavaScript.  
#### What are the relevant issues?
https://github.com/springfox/springfox/issues/1296

### CODE REVIEW

**Comment by igor-sokolov** [comment]
Guys, can you please help me with this PR. When I launched full build on local machine I've got the same error in test cases and it was in the method:
```java
  def "Model substitution registers new rules"() {
    when:
      new Docket(DocumentationType.SWAGGER_12)
              ."${method}"(*args)
              .configure(contextBuilder)
    then:
      context().alternateTypeProvider.rules.size() == expectedSize

    where:
      method                    | args                               | expectedSize
      'genericModelSubstitutes' | [ResponseEntity.class, List.class] | 9
      'directModelSubstitute'   | [LocalDate.class, Date.class]      | 8
  }
``` 

Originally the numbers there were 'genericModelSubstitutes' - 8 and 'directModelSubstitute' - 7. Not sure what it does mean but according to stack tracing the real values were 9 and 7 accordingly. I made decision for myself that this is number of plugins triggered and because I've added one more plugin the numbers should be increased. It worked on my local machine, but I see it doesn't work on CI environment.

What am I doing wrong?

**Comment by dilipkrish** [comment]
Yeah need to fix this test to be jdk agnostic. Right now only jdk 7 is supported.

**Comment by dilipkrish** [comment]
Thanks for the PR :metal:

**Comment by igor-sokolov** [comment]
> Yeah need to fix this test to be jdk agnostic. Right now only jdk 7 is supported.

Hmm, Not sure I know how to fix it. I compiled locally even with jdk 8. Any suggestions/hints?

**Comment by ashutosh-shirole** [comment]
As far as I have seen the implementation of Pattern, I think this might overwrite if there is @Size annotation along with @Pattern annotation on a field. I am not sure but will have to test.

**Comment by igor-sokolov** [comment]
Hi @ashutosh-shirole, you are right. this is behavior that I decided is the best from targets I see in Springfox. I was guided by an idea that RegExp validation is more powerful than  `@Size`, I mean you can do everything what you can with `@Size` and a little bit more:-) For example instead to write `@Size(min = 1, max = 3)` you could provide RegExp like `@Pattern(regexp = "^.{1,3}$")` or better add more specific information like "only digits are allowed": `@Pattern(regexp = "^\d{1,3}$")`. More complexity adds to this questions a case if there are both annotations assigned to the same method/field and they could be in inconsistent state to each other. So in this case the easiest and still correct way to solve this problem seems to me use only `@Pattern` when both annotations assigned, because Springfox this is not in competence to resolve discrepancies in this kind of situation and the main task is only to document API.  If it happens then likely the validation logic in application should not pass correct values and developer will fix the discrepancy. I hope my process of thinking and decision makes sense to you.

**Comment by dilipkrish** [comment]
@igor-sokolov @ashutosh-shirole seems like both PRs end up doing the same thing. 

My 2 💰 is that having 2 mutually exclusive plugins is always better than competing plugins that can overwrite the other ones values as evidenced by [this discussion](https://github.com/springfox/springfox/issues/1231).

It seems like the right thing to do here is to make `pattern` a first class citizen of `ModelProperty` as it is a first class property on the OAS models as well.

**Comment by igor-sokolov** [comment]
Guys, OK. It sounds reasonable to me, especially because the model in Swagger (OAS) has all three type of fields on `StringProperty`, I mean
- io.swagger.models.properties.StringProperty#_enum
- io.swagger.models.properties.StringProperty#minLength and io.swagger.models.properties.StringProperty#maxLength
- io.swagger.models.properties.StringProperty#pattern

I took a look at PR from @ashutosh-shirole and it seems it does exactly what we discussed here. Probably then it makes sense to switch to that PR and close mine.

**Pull request closed without merging**
