### PR TITLE
Only encode the API key when passed in URL query

### PR DESCRIPTION
**Pull request by franklloydteh**
I am current passing tokens through the header. Everything is working using the current app but when trying it on Swagger UI, I noticed that the tokens changed.

### CODE REVIEW

**Comment by dilipkrish** [comment]
@franklloydteh Thanks for the PR!! :+1: Not sure why the syntax highlighting is off. Have you tested that this works?

**Comment by franklloydteh** [comment]
The syntax highlighting was off because there was a missing single quote. Sorry I did not clone the project and just manually edited the file in github. I am not sure on how this should be tested. I just manually edited the source in chrome :1234:

**Comment by dilipkrish** [comment]
My concern was mainly the syntax highlighting. Any who, would you also elaborate how you encountered this issue? I ask because in general API keys are ascii characters and should not be affected by url encoding. i.e it shouldn't have spaces `/` etc.

**Comment by dtritus** [comment]
I've encountered this issue when tried to send API key as `Authorization` header like `Bearer <token>`.
As you can see there is space between `Bearer` and `<token>` and it's being encoded as `%20` right now.

**Comment by dilipkrish** [comment]
@dtritus thanks!

**Comment by BryceMehring** [comment]
@dilipkrish, When is this change going to be included in a release? I'm really needing this functionality.

**Comment by dilipkrish** [comment]
I'm trying to wrap up the release in the next week but it really depends on the outstanding bugs.

**Pull request merged**
