### PR TITLE
Removing Guava dependency

### PR DESCRIPTION
**Pull request by neil1hart**
This PR upgrades the library to Java 8 and removes the Guava dependency.
(Fix issue #1082)
It is similar to PR #2086

The main reason is remove the transitive guava dependency for anything dependent on this library.

Incompatiblilites:
Updates from 1.7 to 1.8 as the minimum Java version.  Rebase pulled in master's java change.
Public API changes where guava constructs have been exposed
Support for Guava Optional in API may have been lost.

What is missing:
I tried to limit the changed lines so there are many areas that can be cleaned up or refactored
- Cleanups (Predicates, Function can be written more compact with java 8)
- Duplicate code, like the replacement for Strings.nullToEmpty()

### CODE REVIEW

**Comment by neil1hart** [comment]
I missed some needed changes that I commented out.  Will get it updated by tonight.

**Comment by neil1hart** [comment]
org.reflections is breaking java 8 guava also.  I'm looking at that also

**Comment by dilipkrish** [comment]
@neil1hart there is a PR for replacing reflections.

**Comment by dilipkrish** [comment]
BTW ❤️ the detailed incremental commits! Thank you for being taking the extra effort to make reviewing PRs easy!

**Comment by neil1hart** [comment]
Should I continue to look at increasing the coverage or is the slight decrease OK?  I can't quite figure out where to add except maybe adding a test for guava Optional in a controller but need the Reflection replacement PR.  I replaced the the guava Optional in BugsController with java.
I'll continue to rebase.

**Comment by dilipkrish** [comment]
@neil1hart thank you very much for a very detailed and thorough PR. It made pulling it in so much easier!

**Comment by ArchangelX360** [comment]
@dilipkrish Hey, do we have a rough estimation when this will be published?

**Comment by dilipkrish** [comment]
Around september... mostly waiting on OAS 3.0 and #2056

**Comment by ArchangelX360** [comment]
Oh alright, do your best :). Thanks

**Comment by sourabhsparkala** [comment]
Hello All, I was wondering when are you planning for a release with this change? Please let me know.

**Pull request merged**
