### PR TITLE
 PR JSR-303 support for Request Parameters + Fix 1244 Allowable values not displayed in Apidocs + 1231 Externalizing Api Descriptions

### PR DESCRIPTION
**Pull request by jfiala**
Bean Validations API (JSR-303) support for Request Parameters #1227

### CODE REVIEW

**Comment by jfiala** [comment]
This PR fixes #1227 and #1244

**Comment by jfiala** [comment]
Cleaned up sources, now code coverage needs to get improved.

**Comment by jfiala** [comment]
Added a ApiDescriptionPropertiesReader and associated plugins (Parameter/ExpandedParameter/ModelProperty) to implement #1232

**Comment by carlosjgp** [comment]
@jfiala , Can I help with the code coverage?

It will be nice if this pull request is accepted!

**Comment by jfiala** [comment]
Yes, great -please feel free to do so, I didn't have time so far...

**Comment by jfiala** [comment]
@dilipkrish  I cleaned up the obvious codacy-bot notes, but what shall we do with "Avoid unused private fields..." regarding the test helper classes? Can you please assist here to get the PR merged eventually...?

**Comment by dilipkrish** [comment]
Sure I'll take a look at it. Sorry I din't realize adding codacy support will retroactively reviews PRs. 

Also do you mind squashing the merge commits and rebasing against master  plus there are merge conflicts that are probably better handled by you.

**Comment by jfiala** [comment]
I rebased and now I get this (both at my forked repo and in the main repo):
gradle eclipsegrad
* What went wrong:
A problem occurred evaluating root project 'springfox'.
> Failed to apply plugin [id 'springfox-multi-release']
   > Not a valid version. Expecting a version of form <MAJOR.MINOR.PATCH> where e.g. 1.0.0-SNAPSHOT, 1.0.0-1-g10a2eg:

**Comment by dilipkrish** [comment]
Looks like its a bad rebase 😖  ... After the rebase you should only be seeing your commits in your pull request. How did you rebase?

Assuming remote origin => springfox/springfox and remote jfiala => jfiala springfox. Is this what you did

```bash
git fetch origin master # gets springfox updates
git rebase origin/master #applies your changes on top of springfox HEAD 
git push jfiala master -f #force push to your master so that your pr is updated.
```

**Comment by jfiala** [comment]
The PR is in order (after some cleanups...), I get the error above when doing clean checkout of https://github.com/springfox/springfox/ as well, so it doesn't seem  to have to do with my commits...

**Comment by jfiala** [comment]
If I view the differences now with jfiala:master, my branch is only 29 commits ahead of the master / 39 files changed? However, I'd like to do a clean build before I create the new PR....

**Comment by dilipkrish** [comment]
What do you see when you do a `git describe`?

**Comment by jfiala** [comment]
Now it looks good, after I've done gradle eclipse, the subproject springfox-spring-web lost its reference to springfox-schema and also added useless classpathentries "test", e.g. for springfox-schema: 
<classpathentry kind="lib" path="C:/projects/springfox/springfox-core/build/classes/test"/>
<classpathentry kind="lib" path="C:/projects/springfox/springfox-core/build/resources/test"/>
...

After cleaning up those I can build again from springfox-master & my master as well.

**Comment by dilipkrish** [comment]
Still doesn't look right. Your PR shouldn't have my commits in it 👇 
screen shot 2016-07-02 at 3 30 54 pm

**Comment by jfiala** [comment]
created a new PR which shows the current state (only my / carlosjgp commits...).

**Pull request closed without merging**
