### PR TITLE
Add minLength and maxLength support from StringProperty

### PR DESCRIPTION
**Pull request by Cthulhu59**
Add support of minLength and maxLength to  StringProperty. Needed if a ModelPropertyBuilderPlugin is created to support \@Min, \@Max and \@Size annotations.

Thanks

### CODE REVIEW

**Comment by dilipkrish** [comment]
@jrhowell / @Cthulhu59 squash?

**Comment by Cthulhu59** [comment]
Yes, I needed changes from @jrhowell for my project so i merged changes in gitdesktop (for the first time, i didn't know that it will be merged to github)

**Comment by dilipkrish** [comment]
@Cthulhu59 I've pushed/merged the pr that this pr depends on. Could you please rebase and squash?

**Comment by Cthulhu59** [comment]
Done

**Comment by dilipkrish** [comment]
Merged via 7afe214aa6faa104dad169119997e1f90704bb72

**Comment by Cthulhu59** [comment]
Thanks ;-)

**Comment by dilipkrish** [comment]
@Cthulhu59 :metal: I squashed your commits and pulled it in manually

**Comment by dilipkrish** [comment]
No :bow: thank you for contributing this fix. :smile:

**Pull request closed without merging**
