### PR TITLE
Supporting for hidden attribute of @ApiParam and @ApiModelProperty annotations.

### PR DESCRIPTION
**Pull request by MaksimOrlov**
**PR** introduces functionality that will support **_hidden_** attributes.
_Unit test_ is provided.
Related issue is #1382

### CODE REVIEW

**Comment by MaksimOrlov** [comment]
I don't know how to make _**circleci**_ pass the unit test.

The error is:

_unable to resolve class springfox.documentation.swagger.readers.parameter.SwaggerExpandedParameterBuilder_

It works perfectly on my laptop. Looks like it isn't able to find class from springfox-swagger-common package.

**Comment by dilipkrish** [comment]
I'll take a look

**Comment by dilipkrish** [comment]
Thanks for the PR! :metal:

**Comment by mzaarour** [comment]
Hi,

Thank you for the PR, i am awaiting for this to work ! 
When do you think we will get this new version  to be downloaded ? 

Thank u

**Comment by dilipkrish** [comment]
Im hoping to get it out by 1st of Oct

**Comment by MaksimOrlov** [comment]
Hi.

@mzaarour

You can build your own snapshot by cloning project and running

```
./gradlew clean build
```

from the root directory of the project.

**Comment by mzaarour** [comment]
Hi all, 

Thank you for your response.  I can wait for the next release.

**Pull request merged**
