### PR TITLE
Add basic Bean validation api (JSR-303) support 

### PR DESCRIPTION
**Pull request by jfiala**
see https://github.com/springfox/springfox/issues/356

Added support for 
* @NotNull
* @Min
* @Max
* @Size

### CODE REVIEW

**Comment by dilipkrish** [comment]
Thanks @jfiala I polished it up some and pushed your pr via https://github.com/springfox/springfox/commit/727e4256b426ad458efbac8907f8a1d05b338cfc

**Comment by dilipkrish** [comment]
Would you please verify I've got it right

**Comment by jfiala** [comment]
It works greatly, but only after adding two null-checks in BeanValidators.java:

``` java
if (propertyDefinition.isPresent()) {
        // 1. not-null-check
    	BeanPropertyDefinition def = propertyDefinition.get();
    	
    	if (def!=null) {
               // 2. not-null-check
    		AnnotatedField field = def.getField();
    		if (field!=null) {
    			notNull = FluentIterable
      		          .from(propertyDefinition.get().getGetter().annotations())
      		          .filter(annotationType)
      		          .first()
      		          .or(FluentIterable
      		              .from(field.annotations())
      		              .filter(annotationType)
      		              .first());
    		}
    		
    	}
      
    }

```

**Comment by dilipkrish** [comment]
Thanks for catching that... fixed via 281e70f27e6584372ec274019bb4ad6ae6b05829

**Pull request closed without merging**
