### PR TITLE
Fixed issue 677

### PR DESCRIPTION
**Pull request by sabyrzhan**
According to issue https://github.com/springfox/springfox/issues/677, set ignoreUnresolvablePlaceholders=true

### CODE REVIEW

**Comment by adrianbk** [comment]
@sabyrzhan want to reproduce this locally before merging.

**Comment by sabyrzhan** [comment]
So how is it in my project: 
1) I used <context:property-placeholder location="file://${property_location}" /> in my spring-integration XML file. 
2) XML file locate in classpath: /META-INF/integration-context.xml
3) And imported that file in my configuration bean:

```java
@Configuration
@ImportResource("classpath:/META-INF/integration-context.xml")
public class IntegrationConfiguration {
    private static final Logger LOGGER = LoggerFactory.getLogger(IntegrationConfiguration.class);
.
.
.
```

**Comment by adrianbk** [comment]
cool. Working on a failing test before I merge your change

**Comment by adrianbk** [comment]
Cool, will merge when the build passes

**Comment by sabyrzhan** [comment]
Will this change be merged and if yes then when with 2.0.0-SNAPSHOT since I am actually using that version?

**Comment by adrianbk** [comment]
@sabyrzhan every successful CI build publishes a SNAPSHOT: https://circleci.com/gh/springfox/springfox/826

**Comment by adrianbk** [comment]
More specifically, every successful build on master publishes a SNAPSHOT.
https://circleci.com/gh/springfox/springfox

I've had to re-run the last build, there was a problem with jcenter - where we publish to!

**Pull request merged**
