### PR TITLE
Fix #2932 - Spring Boot 2.2.2

### LINKED ISSUE #2932: Issue when using Swagger latest version 2.9.2 with Spring boot 2.2.0
Hi, I am running a Spring boot 2.2.0 with swagger version **2.9.2**  and in swagger configuration file if I am using **@Configuration** and **@EnableSwagger2**, getting the following error:

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    springfox.documentation.spring.web.plugins.DocumentationPluginsManager.createContextBuilder(DocumentationPluginsManager.java:152)

The following method did not exist:

    org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;Lorg/springframework/plugin/core/Plugin;)Lorg/springframework/plugin/core/Plugin;

The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:

    jar:file:/Users/SystemName/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.M1/spring-plugin-core-2.0.0.M1.jar!/org/springframework/plugin/core/PluginRegistry.class

It was loaded from the following location:

    file:/Users/SystemName/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.M1/spring-plugin-core-2.0.0.M1.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.plugin.core.PluginRegistry

Any help would be appreciated. 
Thanks!

### PR DESCRIPTION
**Pull request by JoGir**
#### What's this PR do/fix?
* Updated to SpringFramework 5.2.2.RELEASE and Spring Boot 2.2.2.RELEASE.
* Integrated `PluginRegistry` changes

#### Are there unit tests? If not how should this be manually tested?
Nope ¯\\\_(ツ)\_/¯, Compile-Task and tests run successful again

#### Any background context you want to provide?
Not sure about the nullability in `springfox.documentation.schema.plugins.SchemaPluginsManager#viewProvider`, added IllegalStateException if not available.

#### What are the relevant issues?
#2932

### CODE REVIEW

**Comment by JoGir** [comment]
Please rebuild...
``` * What went wrong:
Execution failed for task ':springfox-swagger-ui:nodeSetup'.
> Could not resolve all files for configuration ':springfox-swagger-ui:detachedConfiguration1'.
   > Could not download node-linux-x64.tar.gz (org.nodejs:node:8.12.0)
      > Could not get resource 'https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.gz'.
         > Read timed out`

**Comment by ctruzzi** [comment]
@JoGir Usually closing an re-opening will start a build process.

**Comment by AndreasKl** [comment]
@JoGir There is currently a broken test in your PR, the gist: [Fixed-import-for-model-test](https://gist.github.com/AndreasKl/3bddbcd7b51c7664a77101ee5118d66c) contains a patch which fixes your PR. Maybe you could apply this patch or change the few lines of code.

**Comment by AndreasKl** [comment]
I'll look into why this is broken again.

**Comment by JoGir** [comment]
Some AssertionErrors look like an encoding issue `Expected: 经度 got: ç»åº¦` 😖
and we'll need patches for the `Resource` to `EntityModel` and `Resources` to `CollectionModel` changes.

**Comment by AndreasKl** [comment]
> Some AssertionErrors look like an encoding issue `Expected: 经度 got: ç»�åº¦` confounded
> and we'll need patches for the `Resource` to `EntityModel` and `Resources` to `CollectionModel` changes.

I only had a look at the failing tests from the circleci for the first patch and did not rerun the whole suite, afaics `springfox.documentation.spring.web.dummy.controllers.BugsController` does not work as expected any more. Will have a look.

**Comment by AndreasKl** [comment]
After having fun with those contract test; the new patch:
https://gist.github.com/AndreasKl/666f669bd1b2c6dcc655e356ad88d2d9

```
BUILD SUCCESSFUL in 5m 35s
193 actionable tasks: 139 executed, 54 up-to-date
✔ ~/sc/springfoxbeevolution [bugfix/#2932-spring-boot-2.2.0|●2✚ 15] 
```

**Comment by AndreasKl** [comment]
@dilipkrish Are you planning to support Spring Boot 2.1.x (EOL November 1st 2020) and 2.2.x as 1.x is already EOL? Or should 2.2 support just go to master?

**Comment by SparkMonkey** [comment]
@AndreasKl Do you expect @dilipkrish to come back anytime soon ?

**Comment by AndreasKl** [comment]
@SparkMonkey I talked to him a week ago over LinkedIn and he would like to continue to invest in this project.

**Comment by dilipkrish** [comment]
Than you @JoGir this is super helpful as I get back to working on this project!

**Comment by dilipkrish** [comment]
Thank you @JoGir!!

**Comment by dilipkrish** [comment]
Closes #2932

**Comment by YShane** [comment]
It's still broken in 2.2.3

**Pull request merged**
