### PR TITLE
JacksonEnumDeterminer to handle JsonFormat.Shape.Object

### PR DESCRIPTION
**Pull request by yelhouti**
#### What's this PR do/fix?
Handles JsonFormat.Shape.Object when used on Enums properly. to Threat them as objects instead of Enums
#### Are there unit tests? If not how should this be manually tested?
Yes
#### Any background context you want to provide?
Mabye it's a good idea to provide integration tests
#### What are the relevant issues?
https://github.com/springfox/springfox/issues/1818

### CODE REVIEW

**Comment by yelhouti** [comment]
Could you please re run the test, jcenter.bintray.com was donw for few seconds I think

**Comment by dilipkrish** [comment]
Are you trying to compile it with gradle before you pushed it up? None of the tests are compiling

**Comment by dilipkrish** [comment]
Also would you mind adding a contract/integration test for your use case? There seems to be no tests for that. Basically it would exercise your change in the [`FeatureDemostrationService`](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/FeatureDemonstrationService.java) and will add to the demonstrated features.

**Comment by dilipkrish** [comment]
Thanks @yelhouti

**Comment by yelhouti** [comment]
Thank you :)

**Pull request merged**
