### PR TITLE
Springfox #845: Configuration for global Operation-Parameters.

### PR DESCRIPTION
**Pull request by GitVhaos**
Added support for configuration of global operation parameters.

### CODE REVIEW

**Comment by dilipkrish** [comment]
@GitVhaos sorry I had forgotten about this! i'll take a look and merge it in if everything looks ok! Thanks very much for your pr! :+1:

**Comment by dilipkrish** [comment]
@GitVhaos would be awesome if you could also update the docs :+1:

**Comment by GitVhaos** [comment]
I`m new to gitHub... Where can I update the docs? ^^

**Comment by dilipkrish** [comment]
Depends on what you're trying to document... but [here is the directory](https://github.com/springfox/springfox/tree/master/asciidoc) where the documentation lives.

**Comment by thadc23** [comment]
Is there a way to hide/show these global parameters by `HttpMethod`? For example, I have a header param that I only want on every POST, PUT, and PATCH operation, but not on the others.  Before I give it a shot with a PR, I wanted to make sure it wasn't already possible and I was just missing it.

**Comment by dilipkrish** [comment]
@thadc23 yes there is way, but at the moment you'd have to partition your apis into multiple dockets. So it will apply global parameters per docket. I believe there is a feature request to allow global parameters using a selector predicate. But it may be marked as a "Someday Maybe" feature. (I'll update this thread once I find it)

Let me know if you need any help working through it.

**Comment by thadc23** [comment]
@dilipkrish Were you ever able to find the feature for global params using a selector predicate?  For a relatively small change and to implement filtering by method, I could add a List of HttpMethods to the Parameter and change the OperationParameterReader to filter the global list by the current operation's http method before adding the globals to the parameters for that operation.

To ensure backwards compatibility, I would add a second constructor to the Parameter that accepts a list of HttpMethods and have the current constructor call the new one with the List of all HttpMethods.

Thoughts?

**Comment by dilipkrish** [comment]
I think there is a solution [described here](https://github.com/springfox/springfox/issues/755) that is preferable.

**Comment by dilipkrish** [comment]
Basically creating a plugin that adds parameters conditionally.

**Comment by thadc23** [comment]
Got it working using the plugin.  Thanks.

**Comment by dilipkrish** [comment]
👍

**Comment by avineshsachan** [comment]
Can we set GlobalOperationParameters in Docket Bean at run time as a authentication Token:

doc.select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                        
          .build().globalOperationParameters(Lists.newArrayList(new ParameterBuilder()
          .name("sso-token")
          .description("Description of someGlobalParameter")
          .modelRef(new ModelRef("string"))
          .parameterType("header")
          .required(true).defaultValue("Run Tme Value get from SSO Service")
          .build()));

**Comment by avineshsachan** [comment]
__

Can we set GlobalOperationParameters in Docket Bean at run time as a authentication Token:

docket.select()
.apis(RequestHandlerSelectors.any())
.paths(PathSelectors.any())
.build().globalOperationParameters(Lists.newArrayList(new ParameterBuilder()
.**name("sso-token")**
.description("Description of someGlobalParameter")
.modelRef(new ModelRef("string"))
.parameterType("header")
.required(true).defaultValue**_("Run Tme Value get from SSO Service")_**
.build()));

**Pull request merged**
