### PR TITLE
CWE-117 fix

### PR DESCRIPTION
**Pull request by viananicolas**
#### What's this PR do/fix?
This PR fixes the CWE-117 vulnerability as reported by @jackatsw
#### Any background context you want to provide?
https://stackoverflow.com/a/58623439/4634501
#### What are the relevant issues?
https://github.com/springfox/springfox/issues/3508

### CODE REVIEW

**Comment by StephanHCB** [comment]
Just noticed that this touches the same lines of code I addressed in https://github.com/springfox/springfox/pull/3568, only this does not also address newline injections (log forgery attack), only html injections.

I must say, I like htmlEncoding better than my urlEncoding version, both for the simplicity in code and for readability in the logs, but in order to fully fix all issues including log injection you'd have to also escape newlines (\n, \r) in some manner.

Also have a look at the contract test coverage I added in my PR, completing coverage of the 2 controller classes. I think our PRs could be combined to form an even better solution.

**Comment by samarara** [comment]
Any updates on this?

**Comment by Alos** [comment]
This is still an issue:

https://snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-674160

**Comment by vkkadian** [comment]
Will this ever get fixed?

**Comment by t0r0X** [comment]
> This is still an issue:
> 
> https://snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-674160

Please note the updated Snyk advisory summary:
```
The advisory has been revoked - it doesn't affect any version of package io.springfox:springfox-swagger-ui
[...]
Amendment
This was deemed not a vulnerability.
```

**Review by dvirsegal — COMMENTED** [review]
This is an important fix that exposes security issue as synk and WhitSource scanner identify
https://security.snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-1317096

**Comment by sourabhsparkala** [comment]
@dvirsegal is there any release date available for this? Any update would be helpful thank you.

**Comment by dvirsegal** [comment]
@sourabhsparkala 
Well, I too asked this question, trying to push for a fix. It really depends on the repo maintainers to decide.

**Pull request closed without merging**
