### PR TITLE
X-Forwarded-Prefix should replace basePath in newer spring versions

### PR DESCRIPTION
**Pull request by rainoko**
#### What's this PR do/fix?
since spring 4.3.15/5.0.5 x-forwarded-prefix replaces basePath

#### Are there unit tests? If not how should this be manually tested?
there are unit tests.
#### What are the relevant issues?
#2448

### CODE REVIEW

**Comment by rainoko** [comment]
It seems that codecov is littlebit too strict for my work. Actually there wasn't any unittest for HostNameProvider. I added tests for version specific part. But all other code is just as it was before. So I didnt do test there.

Also it seems that version check code is actually covered but codecov thinks that some part of it is not.

**Comment by dilipkrish** [comment]
@rainoko thanks for the PR! Will merge it in shortly! 🤘

**Comment by dilipkrish** [comment]
@rainoko is there a reason why the spring version is restricted to 5.0.5 and not just be set to greater than 5.0.0?

**Comment by rainoko** [comment]
According https://jira.spring.io/browse/SPR-16650

Fix versions 4.3.15, 5.0.5

**Comment by dilipkrish** [comment]
Yeah I noticed that after messaging you :) thanks for your PR!

**Pull request merged**
